import Head from 'next/head';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import Layout from '@/components/Layout';
import Image from 'next/image';
import profilepic from "../../public/images/profile/Simranpreet.png";
import AnimatedText from '@/components/AnimatedText';
import { LinkArrow } from '@/components/icons';
import HireMe from '@/components/HireMe';
import TransitionEffect from '@/components/TransitionEffect';



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Simranpreet Singh | Home </title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <TransitionEffect/>
      <main className ='flex items-center text-dark w-full min-h-screen '  >
      <Layout className='pt-0 md:pt-16 sm:pt-8 '>
        <div className='flex items-center justify-between w-full lg:flex-col '>
          <div className='w-1/2 md:w-full '>
            <Image src={profilepic}   alt="image of a developer" className="w-full  h-auto   lg:hidden md:inline-block    md:w-full  "
             priority
            sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw" />
          </div>
          <div className='w-1/2 flex flex-col item-center self-center lg:w-full lg:text-center '>
          
          <AnimatedText text="Turning Vision Into Reality With Code And Design" className='!text-6xl text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl '/>
          <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
          As a skilled NextJS developer, I am dedicated to turning ideas into innovative web applications. 
          Explore my latest projects and articles, showcasing my expertise in Next.js and web development.

          </p>
          <div className=' flex items-center self-start mt-2 lg:self-center'>
          <Link href='/' target='_blank' className='flex items-center bg-dark text-light p-2 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark md:p-2 md:px-4 md:text-base' 
           download={true}
          >Resume
          <LinkArrow className={"w-6 ml-1"}/>
          </Link>
          <Link href="mailto:singsimranpreet916@gmail.com" target='_blank' className='ml-4 text-lg font-medium text-dark underline md:text-base' >Contact us</Link>
          </div>
          </div>
        </div>
      </Layout>
      <HireMe/>
      
      </main>
      </>
  )
}
